quarkus.http.port=6969

# db settings
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=your_username
%prod.quarkus.datasource.password=your_password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/core_db

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=your_username
%dev.quarkus.datasource.password=your_password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/core_db

# image settings
quarkus.container-image.build=true
quarkus.container-image.name=core
quarkus.container-image.group=
quarkus.container-image.tag=latest

# hibernate settings
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# flyway settings
quarkus.flyway.migrate-at-start=true

# ==========================
# Keycloak / OIDC settings
# ==========================

# DEV: keycloak exposed on localhost:8081
%dev.quarkus.oidc.auth-server-url=http://localhost:8081/realms/quarkus
%dev.quarkus.oidc-client.auth-server-url=http://localhost:8081/realms/quarkus

# PROD: keycloak container on docker network
%prod.quarkus.oidc.auth-server-url=http://keycloak:8080/realms/quarkus
%prod.quarkus.oidc-client.auth-server-url=http://keycloak:8080/realms/quarkus

quarkus.oidc.client-id=quarkus
quarkus.oidc.credentials.secret=Zzf7jMGkLbIKIj4qSYKiaAyPfD3vw3sv
quarkus.oidc.application-type=service

#quarkus.oidc.authentication.scopes=openid
quarkus.oidc.authentication.redirect-path=/auth/callback

# Protect all endpoints, but return 401 Unauthorized instead of redirecting
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
# Allow access to /login without authentication
#quarkus.http.auth.permission.public.paths=auth/*
#quarkus.http.auth.permission.public.policy=permit
#quarkus.oidc.end-session-path=/logout/start
#quarkus.oidc.logout.post-logout-path=/logout/goodbye
#quarkus.http.auth.login-page=/login

# OIDC client configuration
quarkus.oidc-client.client-id=${QUARKUS_OIDC_CLIENT_ID:quarkus}
quarkus.oidc-client.credentials.secret=${QUARKUS_OIDC_CLIENT_SECRET:Zzf7jMGkLbIKIj4qSYKiaAyPfD3vw3sv}
oidc-client.realm=${QUARKUS_OIDC_CLIENT_REALM:quarkus}
quarkus.oidc-client.grant.type=code
quarkus.oidc-client.enabled=true

# skip TLS validation for self-signed / internal cert
quarkus.tls.trust-all=true

# Kafka/Redpanda
%dev.kafka.bootstrap.servers=localhost:19092
%prod.kafka.bootstrap.servers=redpanda:9092
mp.messaging.outgoing.user-created-out.connector=smallrye-kafka
mp.messaging.outgoing.user-created-out.topic=user-created
mp.messaging.outgoing.user-created-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=${QUARKUS_CORS_ORIGIN_URL:http://localhost:4200}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,origin,x-requested-with
quarkus.http.cors.exposed-headers=authorization
quarkus.http.cors.access-control-allow-credentials=true